spring:
  messages:
#    basename: locale/message/message
    encoding: UTF-8
#    cache-duration: 3600
  datasource: 
   url: jdbc:postgresql://ballgame.cf34t6glgqj0.us-east-1.rds.amazonaws.com:5432/postgres
#   url: jdbc:postgresql://localhost:5432/postgres
   username: postgres
   password: jasper840831
   driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port : 5000 # aws啟動端口號